spring:
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    addresses: 192.168.159.129
    listener:
      simple:
        acknowledge-mode: manual
#    listener:
#      simple:
#        #指定最小的消费者数量.
#        concurrency: 2
#        #指定最大的消费者数量.
#        max-concurrency: 2
#        #开启ack
#        acknowledge-mode: auto
#      #开启ack
#      direct:
#        acknowledge-mode: auto
#    #支持消息的确认与返回
#    template:true
#      mandatory:

