server:
  port: 8088

spring:
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/bruin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&MultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver

